development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials_or_env("REDIS_URL", default: "redis://localhost:6379/1") %>
  channel_prefix: dreams_saas_template_production

staging:
  adapter: redis
  url: <%= Rails.application.credentials_or_env("REDIS_URL", default: "redis://localhost:6379/1") %>
  channel_prefix: dreams_saas_template_staging
