default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: "<%= ENV.fetch("DB_USER") { "postgres" } %>"
  password: "<%= ENV.fetch("DB_PASSWORD") { "postgres" } %>"

development:
  <<: *default
  database: dreams_saas_template_development

test:
  <<: *default
  database: dreams_saas_template_test

production: &production
  <<: *default
  url: <%= Rails.application.credentials_or_env("DB_URL") %>

staging:
  <<: *production
